ODROID: install full .dtb to /boot to boot from multiple devices
Signed-off-by: Dongjin Kim <tobetter@gmail.com>
Change-Id: Ia974b9bcbfb35b831cc5bd7dfb77e19cbc0e8b41

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -687,12 +687,13 @@ handle_dtb() {
 		fi
 	else
 		local dtb=$(find_dtb_file)
-		echo "Installing $dtb into /boot/dtbs/$kvers/$dtb_dir/$dtb_name" >&2
-		mkdir -p "/boot/dtbs/$kvers/$dtb_dir"
-		cp "$dtb" "/boot/dtbs/$kvers/$dtb_dir/$dtb_name.new"
-		backup_and_install \
-			"/boot/dtbs/$kvers/$dtb_dir/$dtb_name.new" \
-			"/boot/dtbs/$kvers/$dtb_dir/$dtb_name"
+		if [ ! -d /usr/lib/linux-image-$kvers/$dtb_dir ]; then
+			error "Couldn't find DTB files in /usr/lib/linux-image-$kvers/$dtb_dir"
+		fi
+		echo "Installing $dtb_dir into /boot/dtbs/$kvers/$dtb_dir/" >&2
+		mkdir -p "/boot/dtbs/$kvers/$dtb_dir" && \
+			rm -rf "/boot/dtbs/$kvers/$dtb_dir/*"
+		cp -a "/usr/lib/linux-image-$kvers/$dtb_dir" "/boot/dtbs/$kvers/"
 
 		if [ "$dtb_dir" != "." ]; then
 			ln -nfs "$dtb_dir/$dtb_name" "/boot/dtbs/$kvers/$dtb_name"
